version: 2

multi-ecosystem-groups:
  default:
    schedule:
      interval: cron
      cronjob: every day at 7am

updates:
- package-ecosystem: github-actions
  directory: /
  patterns:
  - '*'
  groups:
    github-actions:
      patterns:
      - '*'
  cooldown:
    default-days: 7
  multi-ecosystem-group: default
