repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --line-width=120]
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: 64a97fb7fa63188393d3215c6e312f5f9c6d0f78  # frozen: v1.27.0
  hooks:
  - id: zizmor
    args: [--no-progress, --fix]
- repo: https://github.com/rhysd/actionlint
  rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
  hooks:
  - id: actionlint
    additional_dependencies:
    - github.com/wasilibs/go-shellcheck/cmd/shellcheck@latest
