name: GitHub release

on:
  workflow_call:
  push:
    tags:
    - '*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
    - uses: .github/actions/github-release
