name: GitHub Workflow Immortality

on:
  schedule:
  - cron: 20 0 * * 0
  workflow_dispatch:

jobs:
  keepalive:
    name: GitHub Workflow Immortality
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - name: Keep cronjob based triggers of GitHub workflows alive
      uses: PhrozenByte/gh-workflow-immortality@8c1ebe0c3542d2a477ade857b757eb233dd3166b
      with:
        secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        owner_repos: true
        no_repo_names: true
