name: GitHub Workflow Immortality

on:
  schedule:
  - cron: 20 0 * * 0
  workflow_dispatch:

jobs:
  keepalive:
    name: GitHub Workflow Immortality
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - name: Keep cronjob based triggers of GitHub workflows alive
      uses: PhrozenByte/gh-workflow-immortality@39378c27dcacbc17e6fbf83057d1fc40c574000d # v1.2.0
      with:
        secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        owner_repos: true
        no_repo_names: true
