name: tox-uv

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      env:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: '[""]'
      submodules:
        required: false
        type: boolean
        default: false

permissions: {}

jobs:
  tox:
    name: ${{ inputs.os }} / ${{ matrix.env }}${{ inputs.arch != '[""]' && format(' /  {0}', matrix.arch) || '' }}
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.env) }}
        arch: ${{ fromJSON(inputs.arch) }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        submodules: ${{ inputs.submodules }}
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: |
          ${{
            (matrix.env == 'pypy3' || startsWith(matrix.env, 'pypy3-')) && 'pypy3.11' ||
            (matrix.env == 'py310' || startsWith(matrix.env, 'py310-')) && '3.10' ||
            (matrix.env == 'py311' || startsWith(matrix.env, 'py311-')) && '3.11' ||
            (matrix.env == 'py312' || startsWith(matrix.env, 'py312-')) && '3.12' ||
            (matrix.env == 'py313' || startsWith(matrix.env, 'py313-')) && '3.13' ||
            '3.14'
          }}
        architecture: ${{ matrix.arch }}
      if: matrix.env != 'py315' && !startsWith(matrix.env, 'py315-')
    - uses: deadsnakes/action@e640ac8743173a67cca4d7d77cd837e514bf98e8 # v3.2.0
      with:
        python-version: 3.15-dev
      if: matrix.env == 'py315' || startsWith(matrix.env, 'py315-')
    - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      with:
        enable-cache: false
    - run: uv tool install tox --with tox-uv
    - run: tox -e "$MATRIX_ENV"
      env:
        MATRIX_ENV: ${{ matrix.env }}

  collector:
    needs: [tox]
    if: always()
    runs-on: ubuntu-slim
    steps:
    - name: check for failures
      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: echo 'dependent job failed' && exit 1
